services:
  analyst-service:
    build:
      context: ./analystService
      dockerfile: Dockerfile
    container_name: analyst-service
    ports:
      - "8002:8002"
    env_file:
      - .env

  filter-service:
    build:
      context: ./filterService
      dockerfile: Dockerfile
    container_name: filter-service
    ports:
      - "8003:8003"
    env_file:
      - .env

  upload-service:
    build:
      context: ./uploadService
      dockerfile: Dockerfile
    container_name: upload-service
    ports:
      - "8004:8004"
    env_file:
      - .env

  mapping-service:
    build:
      context: ./mappingService
      dockerfile: Dockerfile
    container_name: mapping-service
    ports:
      - "8005:8005"
    env_file:
      - .env